import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import vm from 'node:vm';
const context={window:{}};vm.runInNewContext(await fs.readFile('app/library-index.js','utf8'),context);const create=context.window.ArtistLibraryIndex.create;
const artist=(name,extra={})=>({uid:name,name,order:1,tags:[],works:[],...extra});
const names=rows=>Array.from(rows,a=>a.name);
test('可用中文笔名、别名、标签和备注组合检索，保持原资料不变',()=>{const rows=[artist('sora',{alias:'空野',aliases:['Sky Painter'],tags:['自然光'],note:'春日 旅行'}),artist('other',{tags:['自然光']})],copy=JSON.stringify(rows),index=create();assert.deepEqual(names(index.select(rows,{query:'SKY 旅行'})),['sora']);assert.deepEqual(names(index.select(rows,{query:'空野 自然光'})),['sora']);assert.equal(index.select(rows,{query:'空野 冬天'}).length,0);assert.equal(JSON.stringify(rows),copy);});
test('分类与标签为交集，评分支持多选与未评分',()=>{const rows=[artist('a',{category:'场景',tags:['柔光','自然'],score:4}),artist('b',{category:'场景',tags:['自然'],score:5}),artist('c',{category:null,tags:['自然']})],index=create();assert.deepEqual(names(index.select(rows,{category:'场景',tags:new Set(['柔光','自然']),scores:new Set([4,5])})),['a']);assert.deepEqual(names(index.select(rows,{category:'待判断',scores:new Set([0])})),['c']);});
test('排序稳定，不修改持久化画师序号或原始数组',()=>{const rows=[artist('z',{score:4}),artist('b',{score:4,works:[{id:'1'}]}),artist('a',{score:5})],index=create();assert.deepEqual(names(index.select(rows,{sort:'score'})),['a','z','b']);assert.deepEqual(names(index.select(rows,{sort:'works'})),['b','z','a']);assert.deepEqual(names(index.select(rows,{sort:'name'})),['a','b','z']);assert.deepEqual(names(index.select(rows,{sort:'order'})),['z','b','a']);assert.deepEqual(names(rows),['z','b','a']);});
test('统计明确区分作品参考与测试图，替换快照时不沿用旧搜索缓存',()=>{const index=create(),rows=[artist('a',{works:[{id:'1'},{id:'2',kind:'test'}]})];const summary=index.summary(rows);assert.equal(summary.images,2);assert.equal(summary.works,1);assert.equal(summary.tests,1);assert.equal(summary.counts.get('待判断'),1);index.select(rows,{query:'a'});const next=[artist('b')];assert.equal(index.select(next,{query:'a'}).length,0);assert.equal(index.summary(next).images,0);});
test('20,000 位画师连续输入时不反复扫描图片与重新生成搜索文本',()=>{let reads=0;const rows=Array.from({length:20000},(_,i)=>artist('artist_'+i,{get works(){reads++;return [{id:'1'}];}})),index=create();index.summary(rows);const built=reads;for(const query of ['art','artist','artist_19','artist_19999'])index.select(rows,{query});index.summary(rows);assert.equal(reads,built,'检索过程复用资料快照索引');assert.deepEqual(names(index.select(rows,{query:'artist_19999'})),['artist_19999']);});
